name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    environment: ci-test  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build TypeScript
        run: yarn build

      - name: Inject environment variables into both .env files
        run: |
          for dir in test myrepo9; do
            echo "USER=${{ secrets.GIT_USERNAME }}" >> $dir/.env
            echo "EMAIL=${{ secrets.GIT_EMAIL }}" >> $dir/.env
            echo "REMOTE_URL=${{ secrets.GIT_REMOTE_URL }}" >> $dir/.env
            echo "PAT=${{ secrets.GIT_PAT }}" >> $dir/.env
          done
      - name: Run tests
        run: yarn test
