name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    environment: ci-test  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build TypeScript
        run: yarn build

      - name: Inject environment variables into .env
        run: |
          echo "USER=${{ secrets.GIT_USERNAME }}" >> .env
          echo "EMAIL=${{ secrets.GIT_EMAIL }}" >> .env
          echo "REMOTE_URL=${{ secrets.GIT_REMOTE_URL }}" >> .env
          echo "PAT=${{ secrets.GIT_PAT }}" >> .env

      - name: Run tests
        run: yarn test
